version: "3.7"
services:
  db:
    image: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zuluru
      MYSQL_USER: zuluru
      MYSQL_PASSWORD: userpassword
    volumes:
      - db:/var/lib/mysql
    networks:
      - default

  app:
    image: zuluru:latest
    build:
      context: .
    volumes:
      - app:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - default

volumes:
  db:
  app:

networks:
  default:
